// <auto-generated />
using EnglishProject.Data;
using EnglishProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EnglishProject.Migrations
{
    [DbContext(typeof(EnglishContext))]
    [Migration("20171024102916_InitialDatabase3")]
    partial class InitialDatabase3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnglishProject.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EnglishLevel");

                    b.Property<byte[]>("PartsToLearnByte");

                    b.Property<byte[]>("PartsWhichWantStudyByte")
                        .IsRequired();

                    b.Property<int>("UserId");

                    b.HasKey("ID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("EnglishProject.Models.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer")
                        .IsRequired();

                    b.Property<int>("Count");

                    b.Property<int>("EnglishLevel");

                    b.Property<string>("Example");

                    b.Property<byte>("GrammarPart");

                    b.Property<int>("TaskType");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("EnglishProject.Models.TaskInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CorrectAnswers");

                    b.Property<DateTime>("DateComplete");

                    b.Property<bool>("InCourse");

                    b.Property<int>("TaskID");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("TaskInfo");
                });

            modelBuilder.Entity("EnglishProject.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<bool>("HasCourse");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LoginingHistoryArray");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("EnglishProject.Models.TaskInfo", b =>
                {
                    b.HasOne("EnglishProject.Models.User")
                        .WithMany("ComplitedTaskHistory")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
